filebeat.inputs:
- type: container
  paths:
    - '${DOCKER_DATA_ROOT}'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}

logging.json: true
logging.metrics.enabled: false

